Correction erreur string propre et débug compilation app pron et guacamole

diff --git a/emu/applications/Makefile b/emu/applications/Makefile
--- a/emu/applications/Makefile
+++ b/emu/applications/Makefile
@@ -1,7 +1,6 @@
 SUBDIRS = guacamole pron
 
-all:  guacamole pron \
-			$(BUILDDIRAPPS)/cube_graph \
+all:  $(BUILDDIRAPPS)/cube_graph \
 			$(BUILDDIRAPPS)/cube_graph_mouse \
 			$(BUILDDIRAPPS)/zen_graph \
 			$(BUILDDIRAPPS)/pong \
@@ -10,7 +9,7 @@ all:  guacamole pron \
 	@for i in $(SUBDIRS); do \
 		printf "\033[1m>>> [$$i]\033[0m\n"; \
 		$(MAKE) $(MFLAGS) -C $$i; \
-		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [OK]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
+		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [\033[32mOK\033[30m]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
 	done
 
 $(BUILDDIRAPPS)/%: %.c
