"Identation" dans les sous-makefiles et tabs après CC/CPPC/LD...

diff --git a/emu/libs/Makefile b/emu/libs/Makefile
--- a/emu/libs/Makefile
+++ b/emu/libs/Makefile
@@ -2,9 +2,9 @@ SUBDIRS = libtacos libtsock pronlib
 
 all:
 	@for i in $(SUBDIRS); do \
-		printf "\033[1m>>> [$$i]\033[0m\n"; \
+		printf "\033[1m   >>> [$$i]\033[0m\n"; \
 		$(MAKE) $(MFLAGS) -C $$i; \
-		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [\033[32mOK\033[0m\033[1m]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
+		if [ $$? = 0 ]; then printf "\033[1m   <<< [$$i] [\033[32mOK\033[0m\033[1m]\033[0m\n"; else printf "\033[31m\033[1m   <<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
 	done
 
 .PHONY: libtacos libtsock pronlib
