Ajout couleurs make :D

diff --git a/emu/libs/Makefile b/emu/libs/Makefile
--- a/emu/libs/Makefile
+++ b/emu/libs/Makefile
@@ -1,15 +1,11 @@
 
-all:  libtacos \
-			pronlib \
-			libtsock
+SUBDIRS = libtacos pronlib libtsock
 
-libtacos:
-	$(MAKE) $(MFLAGS) -C $@
-	
-pronlib:
-	$(MAKE) $(MFLAGS) -C $@
-	
-libtsock:
-	$(MAKE) $(MFLAGS) -C $@
+all:
+	@for i in $(SUBDIRS); do \
+		printf "\033[1m>>> [$$i]\033[0m\n"; \
+		$(MAKE) -s -C $$i; \
+		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [OK]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
+	done
 
 .PHONY: libtacos pronlib libtsock
