Amélioration Makefiles.

diff --git a/emu/Makefile b/emu/Makefile
--- a/emu/Makefile
+++ b/emu/Makefile
@@ -1,5 +1,6 @@
+# Colorize outputs
 HASCOLOR = $(shell if test `which colorgcc`; then echo true; else echo false; fi)
-ifneq ($(HASCOLOR),true)
+ifneq ($(HASCOLOR), true)
 	export CC=@printf "\033[34m   CC   $$@\033[0m\n" && gcc
 else
 	export CC=@printf "\033[34m   CC   $$@\033[0m\n" && colorgcc
@@ -7,54 +8,43 @@ endif
 
 export CXX=@printf "\033[34m   CPPC   $$@\033[0m\n" && g++
 
-
 export AR=@printf "\033[32m   AR   $$@\033[0m\n" && ar
 
 export LD=@printf "\033[31m   LD   $$@\033[0m\n" && ld
 
+# Compilation flags
 DEBUG=-DDEBUG
 CURRENTDIR=$(realpath .)
-INCLUDES= -I. -I$(CURRENTDIR)/include/ -I$(CURRENTDIR)/drivers/include/ -I$(CURRENTDIR)/libs/libtacos/include/ -I$(CURRENTDIR)/libs/pronlib/ -I$(CURRENTDIR)/libs/libtsock/
-CFLAGS=-Wall -g $(DEBUG)
-CXXFLAGS=-Wall -g $(DEBUG)
-
+export INCLUDES= -I. -I$(CURRENTDIR)/include/ -I$(CURRENTDIR)/drivers/include/ -I$(CURRENTDIR)/libs/libtacos/include/ -I$(CURRENTDIR)/libs/pronlib/ -I$(CURRENTDIR)/libs/libtsock/
+export CFLAGS=-Wall -g $(DEBUG)
+export CXXFLAGS=-Wall -g $(DEBUG)
 export MFLAGS=-s
 
+# Build paths
 BUILDDIR=$(realpath .)/build
-BUILDDIROBJECT=$(BUILDDIR)/objects
-BUILDDIRLIBS=$(BUILDDIR)/libs
-BUILDDIRAPPS=$(BUILDDIR)/applications
+export BUILDDIROBJS=$(BUILDDIR)/objects
+export BUILDDIRLIBS=$(BUILDDIR)/libs
+export BUILDDIRAPPS=$(BUILDDIR)/applications
 
-LIBTACOS=$(BUILDDIRLIBS)/libtacos.so
-PRONLIB=$(BUILDDIRLIBS)/pronlib.so
-LIBTSOCK=$(BUILDDIRLIBS)/libtsock.so
-
-export LIBTACOS
-export PRONLIB
-export LIBTSOCK
-
-export INCLUDES
-export CFLAGS
-export CXXFLAGS
-
-export BUILDDIROBJECT
-export BUILDDIRLIBS
-export BUILDDIRAPPS
+# Path to libraries
+export LIBTACOS=$(BUILDDIRLIBS)/libtacos.so
+export PRONLIB=$(BUILDDIRLIBS)/pronlib.so
+export LIBTSOCK=$(BUILDDIRLIBS)/libtsock.so
 
 SUBDIRS = drivers libs applications
 
+# Make all subdirectories
 all:
 	@for i in $(SUBDIRS); do \
 		printf "\033[1m>>> [$$i]\033[0m\n"; \
 		$(MAKE) $(MFLAGS) -C $$i; \
-		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [\033[32mOK\033[0m]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
+		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [\033[32mOK\033[0m\033[1m]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
 	done
 
 debug:
 	$(MAKE) $(MAKEFILE) DEBUG="-DDEBUG"
 
-
 clean:
-	rm -f $(BUILDDIROBJECT)/* $(BUILDDIRLIBS)/* $(BUILDDIRAPPS)/*
+	rm -f $(BUILDDIROBJS)/* $(BUILDDIRLIBS)/* $(BUILDDIRAPPS)/*
 
-.PHONY: applications drivers clean libs
+.PHONY: clean $(SUBDIRS)
diff --git a/emu/applications/Makefile b/emu/applications/Makefile
--- a/emu/applications/Makefile
+++ b/emu/applications/Makefile
@@ -1,16 +1,11 @@
+APPS = cube_graph cube_graph_mouse zen_graph pong snake_graph pouet clock_graph
 SUBDIRS = guacamole pron
 
-all:  $(BUILDDIRAPPS)/cube_graph \
-			$(BUILDDIRAPPS)/cube_graph_mouse \
-			$(BUILDDIRAPPS)/zen_graph \
-			$(BUILDDIRAPPS)/pong \
-			$(BUILDDIRAPPS)/snake_graph \
-			$(BUILDDIRAPPS)/pouet \
-			$(BUILDDIRAPPS)/clock_graph
+all: $(addprefix $(BUILDDIRAPPS)/, $(APPS))
 	@for i in $(SUBDIRS); do \
 		printf "\033[1m>>> [$$i]\033[0m\n"; \
 		$(MAKE) $(MFLAGS) -C $$i; \
-		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [\033[32mOK\033[0m]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
+		if [ $$? = 0 ]; then printf "\033[1m<<< [$$i] [\033[32mOK\033[0m\033[1m]\033[0m\n"; else printf "\033[31m\033[1m<<< [$$i] [FAIL]\033[0m\n"; exit 1; fi; \
 	done
 
 $(BUILDDIRAPPS)/%: %.c
@@ -19,4 +14,4 @@ $(BUILDDIRAPPS)/%: %.c
 $(BUILDDIRAPPS)/%: %.cpp
 	$(CXX) -o $@ $< $(LIBTACOS) $(PRONLIB) $(LIBTSOCK) $(CFLAGS) $(INCLUDES)
 
-.PHONY: clean guacamole
+.PHONY: clean $(SUBDIRS)
